# Uncomment the next line to define a global platform for your project
    platform :ios, '9.0'

target 'MSBlog' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MSBlog
    pod 'Masonry', '~> 1.1.0'
    pod 'Hero', '~> 1.4.0'
    pod 'AFNetworking', '~> 3.2.1'
    pod 'SDWebImage', '~> 5.0.0'

end
